### ISSUE TITLE
TypeScript error "not assignable to parameter of type 'never'" for mockResolvedValue after upgrading jest-mock-extended to 4.0.0

### ISSUE THREAD

**Issue by tlevesque-ueat** [timkindberg/jest-when#109]
When using jest-when to train an async method of a mocked object, `mockResolvedValue` expects an argument of type `never`. This causes the following code to fail to compile:

```typescript
import { mock } from 'jest-mock-extended';
import { when } from 'jest-when';

interface Foo {
  bar(): Promise<boolean>;
  baz(): boolean;
}

describe('bug', () => {
  test('this is broken', () => {
    const fooMock = mock<Foo>();
    when(fooMock.bar).mockResolvedValue(true); // error TS2345: Argument of type 'true' is not assignable to parameter of type 'never'.
  });

  test('works fine with mockReturnValue', () => {
    const fooMock = mock<Foo>();
    when(fooMock.baz).mockReturnValue(true);
  });

  test('works fine with jest.fn', () => {
    const fn = jest.fn<Promise<boolean>, []>();
    when(fn).mockResolvedValue(false);
  });
});
```

Notes:
- This issue started happening after upgrading jest-mock-extended to 4.0.0.
- It only happens for async functions (no problem with `mockReturnValue`)
- It only happens for methods of mocked objects (not with mock functions made with `jest.fn`)

To be honest I'm not sure if the problem comes from jest-when or from jest-mock-extended. I suspect the former, because if I just do `fooMock.mockResolvedValue(true)`, without using `when`, it works fine (but I can't just do that to fix the problem because it doesn't have the same argument matching behavior as jest-when).

**Comment by timkindberg** [comment]
Thanks for reporting... maybe I'll try having Codex fix this, stay tuned.

**Comment by tlevesque-ueat** [comment]
> For testing purposes, I manually edited the node_modules/@types/jest-when/index.d.ts

Ah, I see. Not really a viable option for me, I need this to work in CI... But I think it's possible to make such a fix in a clean way, I'll look into it.

**Comment by timkindberg** [comment]
I've tried rewriting in TS several times using AI but I'm always so paranoid that it'll break something if I release it 😬 and there are some lint errors still. I can try again soon.

**Comment by timkindberg** [comment]
Published a newer prerelease, can you try it? jest-when@3.8.1-1 to be exact (or jest-when@next)

**Comment by timkindberg** [comment]
Hey, just wanted to drop a quick note — v4.0.0 is out now as a stable release! 🥳 https://github.com/timkindberg/jest-when/releases/tag/v4.0.0

Thanks again @tlevesque-ueat for the repros and patience while I worked through this. Really helpful.

One thing that makes me feel a lot better going forward — the repo now verifies against both Jest 29 and a dedicated Jest 27 compat workspace, so regressions like this should be a lot harder to miss.
